### ISSUE TITLE
蒲公英新增了上传的api

### ISSUE THREAD

**Issue by yxyaxng** [centerzx/UploadApkPlugin#3]
https://www.pgyer.com/doc/view/api#fastUploadApp，
![image](https://user-images.githubusercontent.com/24906252/185307627-40da358a-3bff-41e0-abaf-d228d9d0cf0c.png)
旧接口要被废弃了

**Comment by centerzx** [comment]
感谢老铁反馈，计划更新一波！

**Comment by centerzx** [comment]
已根据文档更新，感谢~

**Comment by yxyaxng** [comment]
好的，感谢
