### ISSUE TITLE
发送飞书消息参数错误

### ISSUE THREAD

**Issue by aaaaaaaazmx** [centerzx/UploadApkPlugin#4]
send to feishu request json：{"content":{"post":{"zhCn":{"title":"\u5f00\u53d1\u6d4b\u8bd5\u5305V1.0","content":[[{"href":null,"userId":null,"text":"\u6700\u65b0\u5f00\u53d1\u6d4b\u8bd5\u5305\u5df2\u7ecf\u4e0a\u4f20\u81f3\u84b2\u516c\u82f1, \u53ef\u4ee5\u4e0b\u8f7d\u4f7f\u7528\u4e862022-08-25 15:35:19","tag":"text"},{"href":"https://www.pgyer.com/m8Zn","userId":null,"text":"\u70b9\u51fb\u8fdb\u884c\u4e0b\u8f7d","tag":"a"}]]}}},"msgType":"post"}
send to feishu result：{"code":19002,"data":{},"msg":"params error, msg_type need"}

**Comment by centerzx** [comment]
好的。以前飞书没有测过，我这边修复下！抱歉~

**Comment by alizhijun** [comment]
可以增加一个提取本地git信息的功能吗？ 然后发送到飞书，这个其实也挺有用的。

**Comment by aaaaaaaazmx** [comment]
没有飞书的话，我这边可以提供飞书的webHookHostUrl

**Comment by centerzx** [comment]
感谢，我这边已经做了修改。我测试下吧。加个好友：277986425

**Comment by alizhijun** [comment]
原因是你修改的msg_type的字段名问题

**Comment by aaaaaaaazmx** [comment]
原因就是你修改的msg_type的字段名问题，用curl去测试，字段名改为msg_type就无问题了。
