### ISSUE TITLE
是否新增加固?

### ISSUE THREAD

**Issue by j-gin** [centerzx/UploadApkPlugin#5]
您好，是否考虑新增加固功能？

**Comment by centerzx** [comment]
加固的话，感觉导致整个流程时间比较长。不过也可以考虑。感谢老铁建议。

**Comment by centerzx** [comment]
加固流程较长和各个公司使用的加固方案可能不同，为了支持上传加固包，支持通过配置apk文件路径进行上传，达到此效果。
